### ISSUE TITLE
SyntaxError: Unexpected Token = 

### ISSUE THREAD

**Issue by cjvdev3** [lballore/lgtv-alexa-skill#1]
I don't know much on node.js syntax but this is exactly the type of bridge I am looking for...

After a settings my mac / ip for my tv, running npm install, I try running node index.js alexa and get a error: 
/lgtv-alexa-skill-master/node_modules/fauxmojs/lib/index.js:11 constructor(options = {}) {

SyntaxError: Unexpected Token = (between options and {})

Also, will this bridge work with the new v2 firmware that runs on the Echo Plus and newer echo devices?

**Comment by lballore** [comment]
Hi!

Sounds weird. Check out your config.json and look that both your MAC and ip are filled up correctly, and also make sure that all the dependencies are correctly installed and updated. I've not been able to reproduce your error. About the firmware, it should be compatible. I cannot be sure though I don't own any of those new devices. I just wrote the bridge for my personal needs and then shared it :)
