### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by StarfighterJ** [lballore/lgtv-alexa-skill#2]
I need help on exactly how to run this Java Script. not sure how to use npm Install and node index.js alexa.
I am really new at how to get java Scripts to run Please help. 
Thank you 
Jay

**Comment by StarfighterJ** [comment]
Finally figured out to run the index.js alexa  ,but Alexa App does not discover it. The Index.js toast does work on TV

**Comment by lballore** [comment]
It's probably . a problem related to Echo Gen 2 devices (https://github.com/lucone83/lgtv-alexa-skill/issues/3). I close this and keep the other one, related to a similar problem.
