### ISSUE TITLE
Devices are not discoverable

### ISSUE THREAD

**Issue by alanpuccinelli** [lballore/lgtv-alexa-skill#3]
After running "node index.js alexa" and then trying to discover new devices in the alexa app the app just returns "no new devices found"

Pretty sure this is an issue with FauxMo not responding properly to Gen 2 Echo firmware. Opened issue on FauxMoJs project also here:
https://github.com/dsandor/fauxmojs/issues/21

Using Gen 2 Echo
Running on my Mac using OSX 10.13.3

**Comment by lballore** [comment]
I don't have - unfortunately - a Gen 2 Echo device, so I can't really confirm nor deny the problem. I follow the thread...

**Comment by dirkliebich** [comment]
Is there any update on this topic? I seem to have the same issue. All I see is this text

Preparing Amazon Alexa bridge listener...

BUT ALEXA app does not find any service.

**Comment by ggreco** [comment]
Some problem here... with 3rd generation echo... it seems fauxmojs is still not updated...
